### ISSUE TITLE
Why re-implement?

### ISSUE THREAD

**Issue by vitaly-t** [LinZap/node-g-search#2]
Why not use [pg-promise](https://github.com/vitaly-t/pg-promise) instead?

**Comment by martin81930** [comment]
Well, it's because we need to have the full control for a special case in a short time, so we just implement one to finish the job.
And we think it's possible to use your [pg-promise](https://github.com/vitaly-t/pg-promise) in the future. 
We are glad you ask. :smile:

**Comment by vitaly-t** [comment]
> we need to have the full control for a special case

Would you be able to detail? I'm curious if it is something already supported in pg-promise ;)

**Comment by martin81930** [comment]
Actually, developing pg-promise is to coordinate our [node-g-search](https://github.com/LinZap/node-g-search) which is a temp version. Therefore, it may be replaced by your [pg-promise](https://github.com/vitaly-t/pg-promise) or others. :grinning:
